In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]  ## so at 6129th index we are getting 1 rest all are zero.
one_hot_repr

[[6129, 521, 4151, 9854],
 [6129, 521, 4151, 3150],
 [6129, 7380, 4151, 8809],
 [1218, 4326, 1001, 4535, 4734],
 [1218, 4326, 1001, 4535, 6043],
 [6929, 6129, 7273, 4151, 1204],
 [5741, 7168, 5005, 4535]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length) #to set one maximum length so that each sentence have same length.
print(embedded_docs)

[[   0    0    0    0 6129  521 4151 9854]
 [   0    0    0    0 6129  521 4151 3150]
 [   0    0    0    0 6129 7380 4151 8809]
 [   0    0    0 1218 4326 1001 4535 4734]
 [   0    0    0 1218 4326 1001 4535 6043]
 [   0    0    0 6929 6129 7273 4151 1204]
 [   0    0    0    0 5741 7168 5005 4535]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 496ms/step


array([[[ 1.3194267e-02, -4.8244596e-02,  4.4660676e-02, -3.0662306e-03,
          2.3612048e-02, -1.9154811e-02, -3.4746923e-02,  2.8669428e-02,
          3.8889620e-02,  8.1189275e-03],
        [ 1.3194267e-02, -4.8244596e-02,  4.4660676e-02, -3.0662306e-03,
          2.3612048e-02, -1.9154811e-02, -3.4746923e-02,  2.8669428e-02,
          3.8889620e-02,  8.1189275e-03],
        [ 1.3194267e-02, -4.8244596e-02,  4.4660676e-02, -3.0662306e-03,
          2.3612048e-02, -1.9154811e-02, -3.4746923e-02,  2.8669428e-02,
          3.8889620e-02,  8.1189275e-03],
        [ 1.3194267e-02, -4.8244596e-02,  4.4660676e-02, -3.0662306e-03,
          2.3612048e-02, -1.9154811e-02, -3.4746923e-02,  2.8669428e-02,
          3.8889620e-02,  8.1189275e-03],
        [ 2.6816610e-02, -1.9565035e-02,  2.4987329e-02,  2.5220823e-02,
          1.6274642e-02, -1.1904463e-03,  2.6751485e-02, -2.9257501e-02,
          2.4115708e-02, -2.4217654e-02],
        [-4.5504421e-04, -4.6991944e-02,  2.7420372e-04, -1.

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 6129,  521, 4151, 9854])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 104ms/step


array([[ 0.01319427, -0.0482446 ,  0.04466068, -0.00306623,  0.02361205,
        -0.01915481, -0.03474692,  0.02866943,  0.03888962,  0.00811893],
       [ 0.01319427, -0.0482446 ,  0.04466068, -0.00306623,  0.02361205,
        -0.01915481, -0.03474692,  0.02866943,  0.03888962,  0.00811893],
       [ 0.01319427, -0.0482446 ,  0.04466068, -0.00306623,  0.02361205,
        -0.01915481, -0.03474692,  0.02866943,  0.03888962,  0.00811893],
       [ 0.01319427, -0.0482446 ,  0.04466068, -0.00306623,  0.02361205,
        -0.01915481, -0.03474692,  0.02866943,  0.03888962,  0.00811893],
       [ 0.02681661, -0.01956503,  0.02498733,  0.02522082,  0.01627464,
        -0.00119045,  0.02675148, -0.0292575 ,  0.02411571, -0.02421765],
       [-0.00045504, -0.04699194,  0.0002742 , -0.00127039,  0.0253257 ,
         0.04763062,  0.03483028, -0.03731126,  0.00930964, -0.04176674],
       [ 0.01279012,  0.00698679,  0.02134916,  0.02833912, -0.00427578,
        -0.04043995,  0.03327096,  0.02854749